#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

rm log.testCufflinkFoam
    hostname > system/machines
    runApplication blockMesh
    runApplication decomposePar
    runParallel testCufflinkFoam 2 system/machines
