#!/bin/bash
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cd cufflink/cufflink_SmAPCG_Parallel/N500
			
			rm log.testCufflinkFoam

			runApplication blockMesh
			runApplication decomposePar
			
			runParallel testCufflinkFoam 2

